import type { ReactNode } from "react";
import { CommandCenterIcon, type CommandCenterIconId } from "../command-center-icons";
import { CommandActionRow, CommandDetailSurface, CommandNotice, CommandSection, CommandStatusRow, type DetailTone } from "./detail-ui";
import { ReGearPopup } from "./popup-ui";

export const egpuQuickActionIds = ["switch-handheld","safe-disconnect","resolution","disconnect-sleep","disconnect-shutdown","status"] as const;
export type EgpuQuickActionId = typeof egpuQuickActionIds[number];
export type EgpuActionPresentation = {id:EgpuQuickActionId;label:string;detail?:string;tone?:DetailTone;unavailable?:boolean;pending?:boolean;control?:ReactNode};
const actionIcons:Record<EgpuQuickActionId,CommandCenterIconId>={"switch-handheld":"display","safe-disconnect":"safe-disconnect",resolution:"refresh-rate","disconnect-sleep":"safe-disconnect","disconnect-shutdown":"safe-disconnect",status:"egpu"};
const egpuActionStyles=`[data-egpu-action-grid]{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;container-type:inline-size}[data-egpu-action-card]{min-width:0;min-height:72px;padding:7px 8px;border-radius:10px;display:grid;grid-template-columns:auto minmax(0,1fr);grid-template-rows:minmax(0,1fr) auto;column-gap:7px;row-gap:5px;background:#0b2230;border:1px solid #315c75}[data-egpu-action-card][data-tone=warning]{border-color:#80672f}[data-egpu-action-card][data-unavailable=true]{opacity:.62}[data-egpu-action-icon]{display:grid;place-items:center;width:28px;height:28px;border-radius:8px;border:1px solid #315c75;background:#0a2232;color:#c9ecff}[data-egpu-action-copy]{min-width:0}[data-egpu-action-card] strong{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;font-size:10px;line-height:1.15;color:#e7f4fb}[data-egpu-action-card] [data-egpu-action-detail]{display:-webkit-box;-webkit-line-clamp:1;-webkit-box-orient:vertical;overflow:hidden;margin-top:2px;font-size:8.5px;color:#8fb3cc}[data-egpu-action-control]{grid-column:1/-1}[data-egpu-action-control] button{width:100%;min-height:27px;padding:4px 7px;border:1px solid #417895;border-radius:7px;background:#12364b;color:#edf8ff;font:inherit;font-size:9px;font-weight:650}@container (max-width:520px){[data-egpu-action-grid]{grid-template-columns:repeat(2,minmax(0,1fr))}}`;
export function EgpuQuickActions({actions}:{actions:readonly EgpuActionPresentation[]}){return <CommandSection title="eGPU actions"><style>{egpuActionStyles}</style><div data-egpu-action-grid>{actions.map(action=><div key={action.id} data-egpu-action-card data-egpu-action-id={action.id} data-tone={action.tone??"neutral"} data-unavailable={action.unavailable?"true":undefined} aria-busy={action.pending||undefined}><span data-egpu-action-icon><CommandCenterIcon id={actionIcons[action.id]} size={19}/></span><div data-egpu-action-copy><strong>{action.label}</strong>{action.detail&&<span data-egpu-action-detail>{action.detail}</span>}</div>{action.control&&<div data-egpu-action-control>{action.control}</div>}</div>)}</div></CommandSection>}
export function UsbAuthorizationPopup({deviceLabel,detail,authorizeAction,notNowAction,detailsAction}:{deviceLabel:string;detail?:string;authorizeAction?:ReactNode;notNowAction?:ReactNode;detailsAction?:ReactNode}){return <ReGearPopup title="USB authorization required" status={deviceLabel} tone="warning" footer={<>{notNowAction}{detailsAction}{authorizeAction}</>}><CommandDetailSurface><CommandNotice tone="warning" title="Allow this USB device?">{detail??"Authorize this device to continue."}</CommandNotice></CommandDetailSurface></ReGearPopup>}
export function EgpuSleepChoicePopup({connectionLabel,sleepAttachedAction,safeDisconnectSleepAction,cancelAction,detail}:{connectionLabel:string;sleepAttachedAction?:ReactNode;safeDisconnectSleepAction?:ReactNode;cancelAction?:ReactNode;detail?:string}){return <ReGearPopup title="Sleep with eGPU connected" status={connectionLabel} tone="active" footer={<>{cancelAction}{safeDisconnectSleepAction}{sleepAttachedAction}</>}><CommandDetailSurface><CommandNotice tone="active" title="Choose how to sleep">{detail??"Sleep connected, or safely disconnect first."}</CommandNotice></CommandDetailSurface></ReGearPopup>}
export function EgpuPowerActions({safeDisconnectSleepAction,safeDisconnectShutdownAction}:{safeDisconnectSleepAction?:ReactNode;safeDisconnectShutdownAction?:ReactNode}){return <CommandDetailSurface><CommandSection title="Power actions"><CommandStatusRow label="Safe Disconnect + Sleep" value="Optional" tone="warning"/><CommandStatusRow label="Safe Disconnect + Shutdown" value="Optional" tone="warning"/></CommandSection>{(safeDisconnectSleepAction||safeDisconnectShutdownAction)&&<CommandActionRow>{safeDisconnectSleepAction}{safeDisconnectShutdownAction}</CommandActionRow>}</CommandDetailSurface>}
