"""Bind package identity to the selected frontend and backend build policy."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PROFILE_FILENAME = "build_profile.json"
PROFILE_CONFIG_PATH = "backend/regear/delivery/build_profile_config.py"
PROFILE_NAMES = ("development", "production")
POLICIES = {
    "development": "existing_development_surface",
    "production": "stable_allowlist",
}
FEATURES = {
    "development": ["*"],
    "production": ["egpu_connection", "safe_disconnect"],
}


def canonical_bytes(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")


def load_contract(root: Path = ROOT) -> dict[str, Any]:
    """Read the shared profile names/policies without granting runtime access."""
    try:
        contract = json.loads((root / "contracts/build-profiles.json").read_text(encoding="utf-8"))
    except (OSError, UnicodeError, ValueError) as error:
        raise ValueError("release.profile_contract_invalid") from error
    if (
        not isinstance(contract, dict)
        or set(contract) != {"schema_version", "profiles"}
        or type(contract["schema_version"]) is not int
        or contract["schema_version"] != 1
        or contract["profiles"] != {
            name: {"feature_policy": policy, "enabled_features": FEATURES[name]}
            for name, policy in POLICIES.items()
        }
    ):
        raise ValueError("release.profile_contract_invalid")
    return contract


def package_profile(profile: str = "development", *, root: Path = ROOT) -> dict[str, Any]:
    """Resolve package identity; keep the existing development behavior intact."""
    contract = load_contract(root)
    if profile not in PROFILE_NAMES:
        raise ValueError("release.profile_unknown")
    return {
        "schema_version": 1,
        "profile": profile,
        "feature_policy": contract["profiles"][profile]["feature_policy"],
        "enabled_features": contract["profiles"][profile]["enabled_features"],
        "contract_sha256": hashlib.sha256(canonical_bytes(contract)).hexdigest(),
    }


def validate_packaged_profile(value: Any, *, root: Path = ROOT) -> dict[str, Any]:
    """Require explicit, current package identity; never infer production."""
    if not isinstance(value, dict) or not isinstance(value.get("profile"), str):
        raise ValueError("release.archive_profile_invalid")
    expected = package_profile(value["profile"], root=root)
    digest = value.get("bundle_sha256")
    if not isinstance(digest, str) or not re.fullmatch("[0-9a-f]{64}", digest):
        raise ValueError("release.archive_profile_inconsistent")
    expected["bundle_sha256"] = digest
    if type(value.get("schema_version")) is not int or value != expected:
        raise ValueError("release.archive_profile_inconsistent")
    return expected


def backend_config_bytes(profile: str) -> bytes:
    if profile not in PROFILE_NAMES:
        raise ValueError("release.profile_unknown")
    return ("\"\"\"Immutable packaged build profile; generated by build_plugin.py.\"\"\"\n"
            f"BUILD_PROFILE = {profile!r}\n").encode("utf-8")


def frontend_profile(profile: str, *, root: Path = ROOT) -> dict[str, Any]:
    expected = package_profile(profile, root=root)
    try:
        stamp = json.loads((root / "dist" / PROFILE_FILENAME).read_text(encoding="utf-8"))
        digest = hashlib.sha256((root / "dist/index.js").read_bytes()).hexdigest()
    except (OSError, UnicodeError, ValueError) as error:
        raise ValueError("release.frontend_profile_missing: run pnpm build for the requested profile") from error
    expected["bundle_sha256"] = digest
    if stamp != expected:
        raise ValueError("release.frontend_profile_mismatch: rebuild the requested profile")
    return expected


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", choices=PROFILE_NAMES, default="development")
    args = parser.parse_args()
    try:
        result = package_profile(args.profile)
    except ValueError as error:
        parser.exit(1, f"{error}\n")
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
