"""Validate the Decky plugin layout and narrow 0.2 delivery contract."""

from __future__ import annotations

import ast
import json
import sys
import tomllib
from pathlib import Path


REQUIRED_FILES = (
    "LICENSE",
    "scripts/probe_safe_undock_readiness.py",
    "backend/hdm/api.py",
    "backend/hdm/adapters/steamos/sleep_inhibitor.py",
    "backend/hdm/adapters/steamos/peripherals.py",
    "backend/hdm/application/support_bundle.py",
    "backend/hdm/delivery/support_export.py",
    "backend/hdm/delivery/gamescope_wrapper.py",
    "backend/hdm/delivery/gamescope_integration.py",
    "backend/hdm/delivery/presentation_config.py",
    "backend/hdm/adapters/steamos/gamescope_user.py",
    "backend/hdm/adapters/presentation_transition.py",
    "backend/hdm/application/presentation_activation.py",
    "backend/hdm/application/supervised_transition.py",
    "backend/hdm/application/safe_disconnect_shutdown.py",
    "backend/hdm/application/shared_transition_journal.py",
    "backend/hdm/application/guarded_process_release.py",
    "backend/hdm/application/docked_igpu_lifecycle.py",
    "backend/hdm/application/docked_igpu_promotion.py",
    "backend/hdm/adapters/steamos/gamescope_session.py",
    "backend/hdm/adapters/steamos/process_signal.py",
    "backend/hdm/delivery/process_release.py",
    "backend/hdm/delivery/docked_igpu_lifecycle.py",
    "backend/hdm/delivery/docked_igpu_scheduler.py",
    "backend/hdm/delivery/diagnostic_logging.py",
    "backend/hdm/delivery/runtime_state.py",
    "backend/hdm/delivery/transition_journal_store.py",
    "backend/hdm/ports/presentation_activation.py",
    "backend/hdm/ports/system_power.py",
    "backend/hdm/ports/gamescope_session.py",
    "backend/hdm/domain/gamescope_session.py",
    "bin/gamescope",
    "bin/steam-launcher",
    "dist/index.js",
    "dist/index.js.map",
    "main.py",
    "package.json",
    "plugin.json",
)
#: Required in the package, generated by `pnpm build`, and deliberately not in
#: version control. A source checkout that has not been built is missing them
#: for a reason the caller can fix, so say so instead of reporting a bare path.
GENERATED_BUILD_OUTPUTS = ("dist/index.js", "dist/index.js.map")
FORBIDDEN_RPC_TERMS = (
    "apply_transition",
    "restart_gamescope",
    "set_gpu",
    "switch_display",
    "signal_process",
    "force_close",
    "approve_docked_igpu",
    "execute_docked_igpu",
)


#: The declared plugin version, and every file that restates it. `package.json`
#: is the source of truth named by `docs/CURRENT_STATE.md`; the rest must agree.
#: Nothing derives these at build time, so a release that edits only some of
#: them ships a plugin reporting a version it is not.
VERSION_SOURCE = "package.json"
VERSION_SITES = (
    "package.json",
    "pyproject.toml",
    "main.py",
    "backend/hdm/delivery/build_info.py",
)


def _package_json_version(text: str) -> str | None:
    value = json.loads(text).get("version")
    return value if isinstance(value, str) else None


def _pyproject_version(text: str) -> str | None:
    value = tomllib.loads(text).get("project", {}).get("version")
    return value if isinstance(value, str) else None


def _main_version(text: str) -> str | None:
    """Read the `"hdm"` entry of `Plugin._support_versions`.

    Scoped to that method rather than to any `"hdm"` key in the module, so an
    unrelated mapping cannot start answering for the declared version.
    """
    for function in ast.walk(ast.parse(text)):
        if not isinstance(function, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if function.name != "_support_versions":
            continue
        for node in ast.walk(function):
            if not isinstance(node, ast.Dict):
                continue
            for key, value in zip(node.keys, node.values):
                if (
                    isinstance(key, ast.Constant)
                    and key.value == "hdm"
                    and isinstance(value, ast.Constant)
                    and isinstance(value.value, str)
                ):
                    return value.value
    return None


def _build_info_version(text: str) -> str | None:
    """Read the `fallback_version` default of `load_public_build_info`."""
    for node in ast.walk(ast.parse(text)):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if node.name != "load_public_build_info":
            continue
        for argument, default in zip(node.args.kwonlyargs, node.args.kw_defaults):
            if (
                argument.arg == "fallback_version"
                and isinstance(default, ast.Constant)
                and isinstance(default.value, str)
            ):
                return default.value
    return None


#: Each version site paired with the reader that extracts its literal.
VERSION_READERS = {
    "package.json": _package_json_version,
    "pyproject.toml": _pyproject_version,
    "main.py": _main_version,
    "backend/hdm/delivery/build_info.py": _build_info_version,
}


def declared_versions(sources: "dict[str, str]") -> "dict[str, str | None]":
    """Map each version site to its literal, or `None` when unreadable.

    Pure: takes already-read file text so the comparison stays testable without
    a checkout on disk.
    """
    versions: dict[str, str | None] = {}
    for relative, read in VERSION_READERS.items():
        text = sources.get(relative)
        if text is None:
            continue
        try:
            versions[relative] = read(text)
        except (ValueError, SyntaxError, TypeError, AttributeError):
            versions[relative] = None
    return versions


def version_failures(versions: "dict[str, str | None]") -> "list[str]":
    """Report every present site that cannot be read or disagrees with the source.

    Absent files are not reported here: `REQUIRED_FILES` already owns which
    files a plugin root must contain, and duplicating that would make this
    check fire on the narrowed roots used to exercise other rules.

    A file that *is* present still fails closed: an unreadable or relocated
    literal is a failure, never a silently skipped site, so moving one of these
    declarations cannot quietly disable enforcement.
    """
    failures = [
        f"could not read the declared version in {relative}"
        for relative in VERSION_SITES
        if relative in versions and versions[relative] is None
    ]
    if failures:
        return failures
    expected = versions.get(VERSION_SOURCE)
    if expected is None:
        return failures
    for relative in VERSION_SITES:
        if relative == VERSION_SOURCE or relative not in versions:
            continue
        found = versions[relative]
        if found != expected:
            failures.append(
                f"{relative} declares version {found!r} but {VERSION_SOURCE}"
                f" declares {expected!r}; all {len(VERSION_SITES)} declarations"
                " must be updated together"
            )
    return failures


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    failures: list[str] = []
    unbuilt_checkout = (root / "rollup.config.js").is_file()
    for relative in REQUIRED_FILES:
        if (root / relative).is_file():
            continue
        if relative in GENERATED_BUILD_OUTPUTS and unbuilt_checkout:
            # Only a source checkout can be rebuilt; an extracted archive has no
            # rollup config and must be repackaged, not built in place.
            failures.append(f"missing {relative}; run `pnpm build` to generate it")
        else:
            failures.append(f"missing {relative}")

    for launcher in ('gamescope', 'steam-launcher'):
        wrapper_path = root / 'bin' / launcher
        if not wrapper_path.is_file():
            continue
        # read_text() silently translates CRLF, masking a Linux bad-interpreter
        # failure. Check the actual executable bytes in checkouts/extracted ZIPs.
        wrapper = wrapper_path.read_bytes()
        if not wrapper.startswith(b"#!/usr/bin/python3\n") or b"\r" in wrapper:
            failures.append(f"bin/{launcher} must have an LF-only /usr/bin/python3 shebang and body")

    manifest_path = root / "plugin.json"
    if manifest_path.is_file():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        if manifest.get("flags") != ["root"]:
            failures.append("plugin.json must request only the root delivery flag")
        description = str(manifest.get("publish", {}).get("description", "")).lower()
        if "sleep safety" not in description:
            failures.append("plugin.json must describe the approved sleep-safety scope")

    main_path = root / "main.py"
    if main_path.is_file():
        tree = ast.parse(main_path.read_text(encoding="utf-8"), filename=str(main_path))
        plugin_classes = [
            node for node in tree.body if isinstance(node, ast.ClassDef) and node.name == "Plugin"
        ]
        public_methods = {
            node.name
            for plugin in plugin_classes
            for node in plugin.body
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            and not node.name.startswith("_")
        }
        allowed_methods = {
            "get_snapshot",
            "get_tdp_status",
            "set_tdp_enabled",
            "apply_tdp_limit",
            "restore_tdp_limit",
            "get_auto_tdp_status",
            "start_auto_tdp",
            "stop_auto_tdp",
            "get_auto_tdp_benchmark_status",
            "run_auto_tdp_benchmark",
            "cancel_auto_tdp_benchmark",
            "get_auto_tdp_preferences",
            "save_auto_tdp_preference",
            "get_peripheral_status",
            "classify_offline_details",
            "get_action_history",
            "get_automatic_dock_status",
            "set_automatic_dock_enabled",
            "get_docked_igpu_status",
            "acknowledge_docked_igpu_status",
            "get_diagnostic_logging_status",
            "enable_diagnostic_logging",
            "disable_diagnostic_logging",
            "preview_support_bundle",
            "save_support_bundle",
            "preview_presentation_preparation",
            "approve_presentation_preparation",
            "prepare_presentation_integration",
            "preview_supervised_tv_switch",
            "approve_supervised_tv_switch",
            "execute_supervised_tv_switch",
            "approve_supervised_portable_switch",
            "approve_supervised_portable_vulkan_trial",
            "approve_supervised_portable_graphics_trial",
            "approve_supervised_steam_trial_preparation",
            "prepare_supervised_steam_trial_integration",
            "execute_supervised_portable_switch",
            "approve_safe_disconnect_shutdown",
            "execute_safe_disconnect_shutdown",
            "acknowledge_supervised_tv_switch",
            "get_supervised_tv_switch_status",
            "get_transition_journal_status",
            "acknowledge_sleep_journal",
            "get_process_release_status",
            "preview_process_release",
            "approve_process_release",
            "execute_process_release",
            "acknowledge_process_release",
            # Live eGPU disconnect: a read-only status a caller may poll,
            # and one serialized removal that needs an explicit display
            # approval of its own. Neither is clearance to unplug.
            "get_egpu_disconnect_status",
            "execute_egpu_disconnect",
            # The player's standing answer about closing one game before a
            # disconnect. Writes a per-game preference and nothing else; the
            # backend still re-derives whether that answer may be stored.
            "remember_game_close_choice",
            "forget_game_close_choice",
            # The game a disconnect closed, claimed once by whichever panel is
            # alive after the session restart that freed the device.
            "take_pending_relaunch",
            # Read-only: what sleeping would take while the eGPU is attached.
            # Sleeps nothing itself; Steam still performs the suspend.
            "get_sleep_readiness",
        }
        if public_methods != allowed_methods:
            failures.append(
                "Decky RPCs must remain limited to diagnostics/logging, read-only offline report classification and peripheral/watcher/action-history status, automatic-dock preference/status, explicit manual/automatic TDP controls and read-only benchmarks/preferences, approved support export, supervised presentation, confirmed shutdown-before-disconnect, and guarded process release, and live eGPU software disconnect with its per-game close preference"
            )

    sources = {}
    for relative in VERSION_SITES:
        path = root / relative
        if path.is_file():
            sources[relative] = path.read_text(encoding="utf-8")
    failures.extend(version_failures(declared_versions(sources)))

    delivery_sources = "\n".join(
        path.read_text(encoding="utf-8")
        for path in (root / "main.py", root / "src" / "backend.ts")
        if path.is_file()
    ).lower()
    for term in FORBIDDEN_RPC_TERMS:
        if term in delivery_sources:
            failures.append(f"delivery layer contains forbidden mutation RPC term {term!r}")

    if failures:
        print("Plugin package check failed:")
        for failure in failures:
            print(f"- {failure}")
        return 1
    print(
        "Plugin package check passed: documented diagnostics, preferences, explicit TDP controls, support export, sleep guard, supervised presentation, confirmed shutdown-before-disconnect, and guarded process release only."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
